language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y byacc

before_script:
  - mkdir -p build dist doc
  # Get the latest fregec.jar to compile the compiler
  - curl -L -o fregec.jar https://github.com/Frege/frege/releases/download/3.23.288/frege3.23.422-ga05a487.jar

script:
  - make runtime fregec.jar dist
